### ISSUE TITLE
The filter attributes (airports and nations) do not work

### ISSUE THREAD

**Issue by d3liaa** [noi-techpark/webcomp-flightdata#25]
I copy and pasted the code from the webcomponent in a blank site to test it. To the default configurations i added the example filters from the README : 
```
  airports='["!HAM", "BER"]'
  nations='["DE"]'
```
but the results for arrivals and departures remained unvaried, thus showing results for Hamburg. I tried the other two examples as well but the results displayed never changed.

Maybe i made something wrong so this is the simple code i used inside the page:
```
<body style="width: 100%; height: 100%">
    <div style="width: 100%; height: 100%; padding:0 1.5rem">
<noi-mobility-atc arrivals="true" buyticket="false" departures="true" header="true" lang="en" map="true" maxage="60"
    maxforecast="5" metricunits="false" realtime="true" regionswitch="true" sidebar="true"
    theme="terminal" airports='["!HAM", "BER"]' nations='["DE"]'></noi-mobility-atc>
<script
    src="https://cdn.webcomponents.opendatahub.bz.it/dist/a15db41f-7483-46b4-ac0e-d63707c31059/noi-mobility-atc.min.js"></script>
    </div>
</body>
```
And this is the result (that never changed for the filters)
![Screenshot 2023-03-13 162110](https://user-images.githubusercontent.com/101118017/224747364-6ee6e239-dbf5-4b8d-a92b-b149e22f60d3.png)

**Comment by mrabans** [comment]
@dulvui can you please accept https://github.com/noi-techpark/webcomp-flightdata/pull/22 as it has a couple of improvments

**Comment by mrabans** [comment]
@d3liaa we'll verify

**Comment by ag0n-e** [comment]
@d3liaa 
Could it be that the component loaded from the CDN is still an old version? Since the last commits have not been merged into prod? @dulvui

**Comment by dulvui** [comment]
@ag0n-e Yes you are right. I merged now #22 and will put that directly into production.
Let me know if everything works fine, then I'll put in production.

**Comment by d3liaa** [comment]
hi! @dulvui did you put it on production? Can i test if it works from the webcomp store?

**Comment by dulvui** [comment]
@d3liaa No I didn't put in production yet.
You can test the webcomponent from the testing store and if everything is fine let me know, then I will deploy to production on Monday.

**Comment by mrabans** [comment]
All working for a while now. Closing issue.
