### ISSUE TITLE
The user expects dates and time in her local timezone and 24hrs format

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/webcomp-flightdata#8]
The webcomponent would be more useful, if the times would be formatted in the 24hours format and translated into the timezone of the user. 

![Screenshot from 2022-06-13 15-13-55](https://user-images.githubusercontent.com/414797/173363275-2f35fc20-97aa-4ef2-ac3c-a473ba5776c4.png)

**Comment by mrabans** [comment]
Local time should be default, the switch parameter between UTC and local time should be a visible on the "easy configuration in the Webcomponent store GUI
